Repository AY2223S2-CS2103-F10-3/tp, pull requests merged in 2023-04, with the labels that each got.

#147 update HelpWindow to include MODCheck's user guide link
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: Must Fix

#144 update user guide for login feature
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/login/CreatePasswordSection.png
  docs/images/login/DefaultLoadingSection.png
  docs/images/login/DefaultLoginSection.png
  docs/images/login/FirstTimeLoginUser.png
  docs/images/login/PasswordCreatedLoadingSection.png
Labels: priority.High, v1.4, Must Fix

#146 remove find command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: Must Fix

#152 Minor changes to resolve PE-D issues
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/tag/ModuleTag.java
Labels: v1.4

#153 update class diagrams in Developer Guide for Login feature
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: v1.4

#156 Branch week12 update ug v2
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: v1.4

#148 update PPP Haiqel
  docs/team/acerizm.md
Labels: v1.4
