Repository AY2223S2-CS2103-F10-3/tp, pull requests merged in 2023-03, with the labels that each got.

#34 remove all `addressbook` and `AB3` references in UG
  docs/UserGuide.md
Labels: priority.High

#58 Add undo command
  README.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UndoManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/UndoManagerTest.java
Labels: type.Story, priority.High, v1.2

#63 Add Filter Command
  docs/UserGuide.md
  docs/images/filter/filterByDescriptionResult.png
  docs/images/filter/filterByEmailResult.png
  docs/images/filter/filterByNameResult.png
  docs/images/filter/filterByPhoneNumberResult.png
  docs/images/filter/filterByTagsResult.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/ContactContainsDescriptionPredicate.java
  src/main/java/seedu/address/model/person/ContactContainsEmailPredicate.java
  src/main/java/seedu/address/model/person/ContactContainsPhoneNumberPredicate.java
  src/main/java/seedu/address/model/person/ContactContainsTagPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: type.Story, priority.High, v1.2

#69 Update undo functionality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Undoable.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, v1.2

#86 update Dev Guide for DeleteMultiple command
  docs/DeveloperGuide.md
  src/test/java/seedu/address/logic/commands/DeleteMultipleIndexCommandTest.java
Labels: priority.High

#88 Modified code to hide the visibility of contact details
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteMultipleIndexCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSingleIndexCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/MatchNamePredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Medium, v1.3

#92 allow person in contact list to be called by names instead of index in commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteByNameCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditByIndexCommand.java
  src/main/java/seedu/address/logic/commands/EditByNameCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/EditByIndexCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.Medium

#102 add password feature
  .gitignore
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserData.java
  src/main/java/seedu/address/model/UserData.java
  src/main/java/seedu/address/storage/JsonUserDataStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserDataStorage.java
  src/main/java/seedu/address/ui/CreatePasswordSection.java
  src/main/java/seedu/address/ui/DefaultLoginSection.java
  src/main/java/seedu/address/ui/LoadingSection.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/java/seedu/address/ui/WelcomeSection.java
  src/main/java/seedu/address/ui/events/AttemptLoginEvent.java
  src/main/java/seedu/address/ui/events/CreatePasswordSuccessfulEvent.java
  src/main/java/seedu/address/ui/events/LoginFailEvent.java
  src/main/java/seedu/address/ui/events/ProceedCreatePasswordEvent.java
  src/main/java/seedu/address/ui/events/SkipCreatePasswordEvent.java
  src/main/resources/view/CreatePasswordSection.fxml
  src/main/resources/view/DefaultLoginSection.fxml
  src/main/resources/view/LoadingSection.fxml
  src/main/resources/view/LoginWindow.fxml
  src/main/resources/view/WelcomePage.css
  src/main/resources/view/WelcomeSection.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteMultipleIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/EditByIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/LoadCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, severity.Low
